In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import random
import copy

variants = [
[ 3, 6, 7, 7, 7 ],
[ 4, 5, 7, 7, 7 ],
[ 4, 6, 6, 7, 7 ],
[ 5, 5, 6, 7, 7 ],
[ 5, 6, 6, 6, 7 ],
[ 6, 6, 6, 6, 6 ],
[ 3, 3, 3, 7, 7, 7 ],
[ 3, 3, 4, 6, 7, 7 ],
[ 3, 3, 5, 5, 7, 7 ],
[ 3, 3, 5, 6, 6, 7 ],
[ 3, 3, 6, 6, 6, 6 ],
[ 3, 4, 4, 5, 7, 7 ],
[ 3, 4, 4, 6, 6, 7 ],
[ 3, 4, 5, 5, 6, 7 ],
[ 3, 4, 5, 6, 6, 6 ],
[ 3, 5, 5, 5, 5, 7 ],
[ 3, 5, 5, 5, 6, 6 ],
[ 4, 4, 4, 4, 7, 7 ],
[ 4, 4, 4, 5, 6, 7 ],
[ 4, 4, 4, 6, 6, 6 ],
[ 4, 4, 5, 5, 5, 7 ],
[ 4, 4, 5, 5, 6, 6 ],
[ 4, 5, 5, 5, 5, 6 ],
[ 5, 5, 5, 5, 5, 5 ],
[ 3, 3, 3, 3, 4, 7, 7 ],
[ 3, 3, 3, 3, 5, 6, 7 ],
[ 3, 3, 3, 3, 6, 6, 6 ],
[ 3, 3, 3, 4, 4, 6, 7 ],
[ 3, 3, 3, 4, 5, 5, 7 ],
[ 3, 3, 3, 4, 5, 6, 6 ],
[ 3, 3, 3, 5, 5, 5, 6 ],
[ 3, 3, 4, 4, 4, 5, 7 ],
[ 3, 3, 4, 4, 4, 6, 6 ],
[ 3, 3, 4, 4, 5, 5, 6 ],
[ 3, 3, 4, 5, 5, 5, 5 ],
[ 3, 4, 4, 4, 4, 4, 7 ],
[ 3, 4, 4, 4, 4, 5, 6 ],
[ 3, 4, 4, 4, 5, 5, 5 ],
[ 4, 4, 4, 4, 4, 4, 6 ],
[ 4, 4, 4, 4, 4, 5, 5 ],
[ 3, 3, 3, 3, 3, 3, 5, 7 ],
[ 3, 3, 3, 3, 3, 3, 6, 6 ],
[ 3, 3, 3, 3, 3, 4, 4, 7 ],
[ 3, 3, 3, 3, 3, 4, 5, 6 ],
[ 3, 3, 3, 3, 3, 5, 5, 5 ],
[ 3, 3, 3, 3, 4, 4, 4, 6 ],
[ 3, 3, 3, 3, 4, 4, 5, 5 ],
[ 3, 3, 3, 4, 4, 4, 4, 5 ],
[ 3, 3, 4, 4, 4, 4, 4, 4 ],
[ 3, 3, 3, 3, 3, 3, 3, 3, 6 ],
[ 3, 3, 3, 3, 3, 3, 3, 4, 5 ],
[ 3, 3, 3, 3, 3, 3, 4, 4, 4 ],
[ 3, 3, 3, 3, 3, 3, 3, 3, 3, 3 ]
]
num_var = len(variants)

S = [
[0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 4, 1, 4, 0, 3, 2, 0, 0, 0, 4, 4, 3, 0, 0, 0, 0, 0, 2, 0, 3],
[0, 0, 3, 0, 4, 1, 4, 0, 0, 0, 4, 0, 0, 0, 1, 3, 0, 3, 4, 0, 0, 0, 1, 3, 1, 2, 0, 0, 0, 2],
[0, 3, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0, 4, 0, 1, 0, 0, 0, 4, 4, 1, 0, 0, 0],
[0, 0, 0, 0, 0, 0, 2, 0, 2, 4, 4, 1, 0, 0, 0, 0, 2, 0, 4, 2, 1, 4, 0, 1, 4, 4, 0, 0, 3, 0],
[0, 4, 0, 0, 0, 3, 4, 1, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 3, 0, 3, 0, 0, 0, 0],
[0, 1, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 3, 2, 0, 0, 3, 1, 0, 0, 0, 0, 2, 0, 3, 0, 2],
[3, 4, 0, 2, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 4, 0, 3, 3, 3, 0, 4, 0, 1, 2],
[2, 0, 0, 0, 1, 0, 0, 0, 3, 1, 0, 4, 3, 0, 0, 0, 1, 2, 1, 0, 0, 0, 3, 3, 0, 4, 0, 1, 0, 0],
[0, 0, 2, 2, 0, 0, 0, 3, 0, 4, 0, 4, 0, 0, 0, 0, 4, 4, 2, 2, 1, 1, 2, 4, 0, 4, 0, 0, 0, 1],
[0, 0, 2, 4, 3, 0, 0, 1, 4, 0, 4, 3, 1, 3, 0, 1, 2, 0, 3, 1, 3, 0, 0, 0, 0, 1, 1, 0, 1, 0],
[4, 4, 0, 4, 0, 0, 0, 0, 0, 4, 0, 4, 0, 0, 0, 4, 1, 1, 0, 0, 0, 1, 0, 0, 4, 0, 2, 0, 0, 0],
[1, 0, 0, 1, 0, 3, 0, 4, 4, 3, 4, 0, 0, 4, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1],
[4, 0, 1, 0, 0, 0, 1, 3, 0, 1, 0, 0, 0, 0, 0, 3, 4, 0, 2, 0, 3, 0, 0, 1, 2, 1, 0, 0, 0, 4],
[0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 0, 4, 4, 0, 0, 0, 4, 0, 4, 0, 3, 0, 1, 0, 0, 0],
[3, 1, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 2, 3, 0, 2, 0, 4, 0, 0, 4, 0, 2, 1],
[2, 3, 0, 0, 0, 3, 0, 0, 0, 1, 4, 0, 3, 4, 3, 0, 0, 0, 0, 0, 3, 1, 0, 0, 0, 4, 1, 0, 1, 3],
[0, 0, 1, 2, 0, 2, 0, 1, 4, 2, 1, 0, 4, 4, 0, 0, 0, 4, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 3, 3],
[0, 3, 0, 0, 0, 0, 2, 2, 4, 0, 1, 0, 0, 0, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 4, 4, 4, 0, 0, 0, 1, 2, 3, 0, 2, 2, 0, 2, 0, 0, 0, 0, 4, 0, 0, 1, 3, 0, 0, 0, 4, 0, 4],
[4, 0, 0, 2, 0, 3, 0, 0, 2, 1, 0, 0, 0, 0, 3, 0, 1, 0, 4, 0, 0, 0, 0, 0, 0, 4, 0, 2, 0, 0],
[4, 0, 1, 1, 2, 1, 4, 0, 1, 3, 0, 0, 3, 4, 0, 3, 0, 2, 0, 0, 0, 4, 4, 3, 4, 3, 0, 0, 3, 0],
[3, 0, 0, 4, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 4, 0, 1, 3, 0, 0, 0, 0, 3, 1],
[0, 1, 0, 0, 0, 0, 3, 3, 2, 0, 0, 0, 0, 4, 0, 0, 1, 0, 1, 0, 4, 1, 0, 0, 0, 0, 1, 0, 4, 0],
[0, 3, 0, 1, 3, 0, 3, 3, 4, 0, 0, 0, 1, 0, 4, 0, 1, 0, 3, 0, 3, 3, 0, 0, 0, 0, 1, 0, 0, 2],
[0, 1, 4, 4, 0, 0, 3, 0, 0, 0, 4, 0, 2, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 3, 0, 0, 3],
[0, 2, 4, 4, 3, 2, 0, 4, 4, 1, 0, 0, 1, 0, 0, 4, 0, 0, 0, 4, 3, 0, 0, 0, 0, 0, 4, 0, 3, 1],
[0, 0, 1, 0, 0, 0, 4, 0, 0, 1, 2, 0, 0, 1, 4, 1, 0, 0, 0, 0, 0, 0, 1, 1, 3, 4, 0, 3, 3, 3],
[2, 0, 0, 0, 0, 3, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 4, 2, 0, 0, 0, 0, 0, 0, 3, 0, 0, 4],
[0, 0, 0, 3, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 2, 1, 3, 0, 0, 0, 3, 3, 4, 0, 0, 3, 3, 0, 0, 4],
[3, 2, 0, 0, 0, 2, 2, 0, 1, 0, 0, 1, 4, 0, 1, 3, 3, 0, 4, 0, 0, 1, 0, 2, 3, 1, 3, 4, 4, 0]

]

In [2]:
def summ(matr, hor, start_c, end_c):
    summa = 0
    for i in range(start_c, end_c):
        summa += matr[hor][i]
    return(summa)

def count_Q (matr, variants):
    displacement = 0 #смещение
    Q = 0
    for container in variants:
        for i in range (displacement, displacement+container):  
            for j in range (displacement+container, len(matr)):
                Q = Q + matr[i][j]
        displacement = displacement + container
    return (Q)

def count_delt_R (matr, container , cont_num, variants):
    delt_R = []
    colum = []
    colum.append(0) #старт контейнера
    displacement = 0
    for i in range (len(variants)):
        colum.append(colum[i]+variants[i]) 
    for i in range (cont_num):  
        displacement += variants[i]
    #Расчет дельта R
    start_hor = displacement - container 
    z = 0 
    for i in range (start_hor, displacement):
        delt_R.append([])
        for j in range (displacement, len(matr)): 
            for k in range (len(colum)):
                if j >= colum[k]:
                    start_cont = colum[k]
                    end_cont = colum[k+1]
                    
            R = summ(matr, i, start_cont, end_cont) - summ(matr, i, start_hor, displacement) + summ(matr, j, start_hor, displacement) - summ(matr, j, start_cont, end_cont) - 2*matr[i][j]
            delt_R[z].append(R)
        z = z+1
    return(delt_R)

def find_max_R(delt_R):
    max_R = delt_R[0][0]
    max_hor = 0
    max_ver = 0
    for i in range (0, len(delt_R)):
        for j in range (0,len(delt_R[0])):
            if (delt_R[i][j] > max_R):
                max_R = delt_R[i][j]
                max_hor = i
                max_ver = j
    return (max_R, max_hor, max_ver)

def find_min_S (S_V, matr):
    min_S = S_V[0] 
    min_num_S = 0 
        
    for i in range (1, len(S_V)):
        if (S_V[i] < min_S): 
            min_S = S_V[i]
            min_num_S = i
        if (S_V[i] == min_S): 
            s_min = 0
            s_i = 0
            for j in range (len(matr[i])):
                if (matr[i][j] > 1):
                    s_i = s_i + 1
                if (matr[min_num_S][j] > 1):
                    s_min = s_min + 1
            if (s_i > s_min):
                min_S = S_V[i]
                min_num_S = i 
                
    return (min_num_S)

In [3]:
Q_min =  1000

for opt in range (num_var):
    matr = copy.deepcopy(S)
    temp_var = variants[opt]
    
    ver_num = [i for i in range (len(matr))] 
    V_i = [] 
    flags = []
    for i in range (len(temp_var)):
        V_i.append([])
        flags.append(0)
        
    for num in range (len(temp_var) - 1): #цикл для заполнения всех контейнеров
        print(matr)
        S_V = [] 
        for i in range (len(matr)):
            S_V.append(sum(matr[i]))
        print ("Количество внешних связей вершин: ", S_V)
        
        min_num_S = find_min_S(S_V, matr)
        temp_V = [] 
        temp_V.append(min_num_S) 
        for i in range (len(matr[min_num_S])):
            if (matr[min_num_S][i] > 0):
                temp_V.append(i) 
        print(temp_V)        
        for i in range (len(temp_var)):
            if (flags[i] == 0):
                container_num = i
                break
        while (len(temp_V) < temp_var[container_num]):
            next_V = []
            for i in range (len(matr)):
                if i not in temp_V: 
                    next_V.append(i)
            S_inc = []
            for i in (next_V):
                S_inc_temp = 0
                for j in (temp_V):
                    S_inc_temp = S_inc_temp + matr[i][j]
                S_inc.append(S_inc_temp)
            print("Контейнер больше, чем нужно.")
            print("Вектор связей:  ", S_inc)
            max_S_pos = S_inc.index(max(S_inc))
            temp_V.append(next_V[max_S_pos])               
                
    
        while (len(temp_V) > temp_var[container_num]):
            delt_V = []
            for i in (temp_V): #Считаем дельты 
                temp_delt = S_V[i]
                for j in (temp_V):
                    temp_delt = temp_delt - matr[i][j]
                delt_V.append(temp_delt)
            print("Контейнер меньше, чем нужно")
            print("Вектор дельт:  ", delt_V)
            max_delt_pos = delt_V.index(max(delt_V))
            temp_V.pop(max_delt_pos)
               
       
        temp_V.sort()
        j = 0
        for i in (temp_V):
            matr = np.delete(matr, i-j, axis=0) 
            matr = np.delete(matr, i-j, axis=1)
            j = j+1
        
       
        for i in range(len(temp_V)):
            flag = 1
            j = -1
            k = 0
            while (flag):
                if (ver_num[k] >= 0):
                    j = j+1
                
                if (j == (temp_V[i])):
                    temp_V[i] = ver_num[k]
                    flag = 0
                k = k + 1 
                                
                    
        for i in (temp_V):
            ver_num[i] = -1
                
        
        flags[container_num] = 1 
        V_i[container_num] = temp_V 
        
        
        
    #Заполняем последний оставшийся контейнер
    for i in range (0, len(temp_var)):
            if (flags[i] == 0):
                container_num = i
                break

    temp_V = []
    for i in range (len(ver_num)):
        if (ver_num[i] >= 0):
            temp_V.append(ver_num[i])

    flags[container_num] = 1 
    V_i[container_num] = temp_V 
    
    
    
    matr = copy.deepcopy(S)
    ver_num = [i for i in range (len(matr))] #порядок вершин сейчас
    k = 0
    for i in V_i:
        for j in i:
            pos_str = ver_num.index(j) 
            #смена местами столбцов    
            for z in range(len(matr)):
                matr[z][pos_str], matr[z][k] = matr[z][k], matr[z][pos_str]   
            #смена местами строк
            matr[pos_str], matr[k] = matr[k], matr[pos_str]
            ver_num[k], ver_num[pos_str] = ver_num[pos_str], ver_num[k]
            k = k+1
    
    #Начало итерационной схемы
    cont_num = 1 
    print("Набор контейнеров ", temp_var)    
    print ("Распределение по контейнерам", V_i)
    for container in temp_var:
        while (cont_num < (len(temp_var))): 
            delt_R = [] 
            Q = count_Q(matr, temp_var)
            print("Целевая функция Q=", Q)
            #Подсчет delt_R
            delt_R = count_delt_R (matr, container, cont_num, temp_var)
            print (delt_R)
            max_R, max_hor, max_ver = find_max_R(delt_R) 
            if (max_R <=0 ):
                break #нет максимума, большего нуля
                
            
            for i in range (cont_num):
                max_ver = max_ver + temp_var[i]
                max_hor = max_hor + temp_var[i]
            max_hor = max_hor - container
              
            for i in range(len(matr)):
                matr[i][max_hor], matr[i][max_ver] = matr[i][max_ver], matr[i][max_hor]   
           
            matr[max_hor], matr[max_ver] = matr[max_ver], matr[max_hor]
            
        cont_num = cont_num + 1
    if (Q < Q_min):
        Q_min = Q
        best_var = temp_var
    print("------------------")
                
        
            
print("Минимальное Q= ", Q_min)    
print("Лучшее разбиение на контейнеры ", best_var)

[[0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 4, 1, 4, 0, 3, 2, 0, 0, 0, 4, 4, 3, 0, 0, 0, 0, 0, 2, 0, 3], [0, 0, 3, 0, 4, 1, 4, 0, 0, 0, 4, 0, 0, 0, 1, 3, 0, 3, 4, 0, 0, 0, 1, 3, 1, 2, 0, 0, 0, 2], [0, 3, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0, 4, 0, 1, 0, 0, 0, 4, 4, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 2, 0, 2, 4, 4, 1, 0, 0, 0, 0, 2, 0, 4, 2, 1, 4, 0, 1, 4, 4, 0, 0, 3, 0], [0, 4, 0, 0, 0, 3, 4, 1, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 3, 0, 3, 0, 0, 0, 0], [0, 1, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 3, 2, 0, 0, 3, 1, 0, 0, 0, 0, 2, 0, 3, 0, 2], [3, 4, 0, 2, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 4, 0, 3, 3, 3, 0, 4, 0, 1, 2], [2, 0, 0, 0, 1, 0, 0, 0, 3, 1, 0, 4, 3, 0, 0, 0, 1, 2, 1, 0, 0, 0, 3, 3, 0, 4, 0, 1, 0, 0], [0, 0, 2, 2, 0, 0, 0, 3, 0, 4, 0, 4, 0, 0, 0, 0, 4, 4, 2, 2, 1, 1, 2, 4, 0, 4, 0, 0, 0, 1], [0, 0, 2, 4, 3, 0, 0, 1, 4, 0, 4, 3, 1, 3, 0, 1, 2, 0, 3, 1, 3, 0, 0, 0, 0, 1, 1, 0, 1, 0], [4, 4, 0, 4, 0, 0, 0, 0, 0, 4, 0, 4, 0, 0, 0, 4, 1, 1, 0, 0, 0, 1, 0, 0, 4, 0, 

Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [7, 26, 15, 17, 29, 12]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [11, 26, 15, 19, 16]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [13, 15, 20, 20]
[[0 0 0 0 0 3 0 0 4 1 4 0 3 2 0 4 3 0 0 0 0 0 0 3]
 [0 0 3 0 4 4 0 0 4 0 0 0 1 3 4 0 0 1 3 1 2 0 0 2]
 [0 3 0 0 0 0 2 2 0 0 1 0 0 0 4 1 0 0 0 4 4 1 0 0]
 [0 0 0 0 0 2 2 4 4 1 0 0 0 0 4 1 4 0 1 4 4 0 3 0]
 [0 4 0 0 0 4 0 3 0 0 0 0 1 0 0 2 0 0 3 0 3 0 0 0]
 [3 4 0 2 4 0 0 0 0 0 1 0 0 0 0 4 0 3 3 3 0 4 1 2]
 [0 0 2 2 0 0 0 4 0 4 0 0 0 0 2 1 1 2 4 0 4 0 0 1]
 [0 0 2 4 3 0 4 0 4 3 1 3 0 1 3 3 0 0 0 0 1 1 1 0]
 [4 4 0 4 0 0 0 4 0 4 0 0 0 4 0 0 1 0 0 4 0 2 0 0]
 [1 0 0 1 0 0 4 3 4 0 0 4 0 0 2 0 0 0 0 0 0 0 0 1]
 [4 0 1 0 0 1 0 1 0 0 0 0 0 3 2 3 0 0 1 2 1 0 0 4]
 [0 0 0 0 0 0 0 3 0 4 0 0 0 4 0 4 0 4 0 3 0 1 0 0]
 [3 1 0 0 1 0 0 0 0 0 0 0 0 3 2 0 2 0 4 0 0 4 2 1]
 [2 3 0 0 0 0 0 1 4 0 3 4 3 0 0 3 1 0 0 0 4 1 1 3]
 [0 4 4 4 0 0 2 3 0 2 2 0 2 0 0 0 0 1 3 0

Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [9, 18, 19, 27, 18]
[[0 0 0 0 0 0 3 0 4 1 4 3 2 0 4 4 0 0 0 0 2 3]
 [0 0 3 0 4 1 4 0 4 0 0 1 3 4 0 0 3 1 2 0 0 2]
 [0 3 0 0 0 0 0 2 0 0 1 0 0 4 0 1 0 4 4 1 0 0]
 [0 0 0 0 0 0 2 4 4 1 0 0 0 4 2 1 1 4 4 0 0 0]
 [0 4 0 0 0 3 4 3 0 0 0 1 0 0 0 2 3 0 3 0 0 0]
 [0 1 0 0 3 0 0 0 0 3 0 3 3 0 3 1 0 0 2 0 3 2]
 [3 4 0 2 4 0 0 0 0 0 1 0 0 0 0 4 3 3 0 4 0 2]
 [0 0 2 4 3 0 0 0 4 3 1 0 1 3 1 3 0 0 1 1 0 0]
 [4 4 0 4 0 0 0 4 0 4 0 0 4 0 0 0 0 4 0 2 0 0]
 [1 0 0 1 0 3 0 3 4 0 0 0 0 2 0 0 0 0 0 0 3 1]
 [4 0 1 0 0 0 1 1 0 0 0 0 3 2 0 3 1 2 1 0 0 4]
 [3 1 0 0 1 3 0 0 0 0 0 0 3 2 3 0 4 0 0 4 0 1]
 [2 3 0 0 0 3 0 1 4 0 3 3 0 0 0 3 0 0 4 1 0 3]
 [0 4 4 4 0 0 0 3 0 2 2 2 0 0 4 0 3 0 0 0 4 4]
 [4 0 0 2 0 3 0 1 0 0 0 3 0 4 0 0 0 0 4 0 2 0]
 [4 0 1 1 2 1 4 3 0 0 3 0 3 0 0 0 3 4 3 0 0 0]
 [0 3 0 1 3 0 3 0 0 0 1 4 0 3 0 3 0 0 0 1 0 2]
 [0 1 4 4 0 0 3 0 4 0 2 0 0 0 0 4 0 0 0 3 0 3]
 [0 2 4 4 3 2 0 1 0 0 1 0 4 0 4 3 0 0 0 4 0 1]
 [0 0 1 0 0 0 4 1 2 0 0 4 

Количество внешних связей вершин:  [20, 23, 17, 16, 13, 21, 18, 21, 27, 17, 24, 20, 18, 26, 23]
[4, 1, 6, 10, 11, 13]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [0, 13, 12, 16, 7, 18]
[[0 0 0 4 2 0 4 0 0 3]
 [0 0 0 1 0 4 0 4 4 0]
 [0 0 0 0 0 4 2 4 4 0]
 [4 1 0 0 3 2 0 2 1 4]
 [2 0 0 3 0 0 0 0 4 3]
 [0 4 4 2 0 0 4 0 0 4]
 [4 0 2 0 0 4 0 0 4 0]
 [0 4 4 2 0 0 0 0 0 3]
 [0 4 4 1 4 0 4 0 0 1]
 [3 0 0 4 3 4 0 3 1 0]]
Количество внешних связей вершин:  [13, 13, 14, 17, 12, 18, 14, 13, 18, 18]
[4, 0, 3, 8, 9]
Набор контейнеров  [5, 5, 5, 5, 5, 5]
Распределение по контейнерам [[7, 8, 10, 16, 17], [5, 9, 11, 13, 27], [6, 21, 22, 26, 28], [1, 4, 14, 20, 23], [0, 12, 15, 25, 29], [2, 3, 18, 19, 24]]
Целевая функция Q= 356
[[-4, 3, -9, -3, -7, -9, -5, -12, -9, -11, -3, -13, -8, -4, -13, -4, -8, -5, -3, -4, -10, -7, -16, -8, -9], [-7, -6, -12, -6, -8, -14, -12, -15, -14, -16, -7, -15, -12, -10, -19, -9, -11, -14, -12, -15, -12, -9, -16, -10, -7], [2, 3, -3, 3, 1, -5, -3, -2, -9, -7

Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [0, 18, 19, 27, 17, 32, 15, 25]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [2, 18, 23, 30, 17, 18, 28]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [5, 18, 23, 17, 18, 29]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [8, 20, 23, 17, 18]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [12, 24, 17, 21]
[[0 0 0 0 3 0 0 4 1 4 0 2 0 4 3 0 0 0 0 0 3]
 [0 0 3 0 4 0 0 4 0 0 0 3 4 0 0 1 1 2 0 0 2]
 [0 3 0 0 0 2 2 0 0 1 0 0 4 1 0 0 4 4 1 0 0]
 [0 0 0 0 2 2 4 4 1 0 0 0 4 1 4 0 4 4 0 3 0]
 [3 4 0 2 0 0 0 0 0 1 0 0 0 4 0 3 3 0 4 1 2]
 [0 0 2 2 0 0 4 0 4 0 0 0 2 1 1 2 0 4 0 0 1]
 [0 0 2 4 0 4 0 4 3 1 3 1 3 3 0 0 0 1 1 1 0]
 [4 4 0 4 0 0 4 0 4 0 0 4 0 0 1 0 4 0 2 0 0]
 [1 0 0 1 0 4 3 4 0 0 4 0 2 0 0 0 0 0 0 0 1]
 [4 0 1 0 1 0 1 0 0 0 0 3 2 3 0 0 2 1 0 0 4]
 [0 0 0 0 0 0 3 0 4 0 0 4 0 4 0 4 3 0 1 0 0]
 [2 3 0 0 0 0 1 4 0 3 4 0 0 3 1 0 0 4 1 1 3]
 [0 4 4 4 0 2 3 0 2 2 0 0 0 0 0 1 

Набор контейнеров  [3, 4, 4, 4, 4, 4, 7]
Распределение по контейнерам [[7, 16, 17], [5, 11, 19, 27], [13, 22, 24, 26], [2, 8, 12, 18], [14, 23, 28, 29], [0, 10, 15, 21], [1, 3, 4, 6, 9, 20, 25]]
Целевая функция Q= 367
[[-5, -8, -2, -7, -4, -7, -6, -5, -2, 5, 2, -5, -7, -8, -3, -4, -12, -8, -8, -6, -4, -6, -14, -9, -7, -8, -14], [-13, -4, -8, -9, -12, -3, -6, -5, -4, 3, 0, -3, -5, -2, -7, -8, -11, -13, -11, -9, -8, -14, -16, -13, -13, -12, -10], [-13, -8, -10, -13, -10, -7, -12, -11, -8, -3, 2, -9, -13, -8, -9, -10, -12, -14, -12, -10, -12, -8, -14, -15, -7, -14, -8]]
Целевая функция Q= 362
[[-9, -12, -8, -10, -10, -12, -12, -11, -7, -5, -3, -10, -10, -12, -6, -8, -16, -14, -14, -13, -4, -8, -13, -9, -10, -9, -14], [-16, -7, -9, -13, -15, -7, -9, -8, -6, -2, -12, -7, -8, -4, -10, -10, -16, -16, -14, -11, -11, -15, -20, -16, -13, -14, -13], [-15, -10, -10, -16, -12, -10, -14, -13, -8, -8, -8, -11, -15, -9, -11, -11, -16, -16, -14, -11, -14, -8, -17, -17, -6, -15, -10]]
Целевая функция Q=

[[0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 4, 1, 4, 0, 3, 2, 0, 0, 0, 4, 4, 3, 0, 0, 0, 0, 0, 2, 0, 3], [0, 0, 3, 0, 4, 1, 4, 0, 0, 0, 4, 0, 0, 0, 1, 3, 0, 3, 4, 0, 0, 0, 1, 3, 1, 2, 0, 0, 0, 2], [0, 3, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0, 4, 0, 1, 0, 0, 0, 4, 4, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 2, 0, 2, 4, 4, 1, 0, 0, 0, 0, 2, 0, 4, 2, 1, 4, 0, 1, 4, 4, 0, 0, 3, 0], [0, 4, 0, 0, 0, 3, 4, 1, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 3, 0, 3, 0, 0, 0, 0], [0, 1, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 3, 3, 2, 0, 0, 3, 1, 0, 0, 0, 0, 2, 0, 3, 0, 2], [3, 4, 0, 2, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 4, 0, 3, 3, 3, 0, 4, 0, 1, 2], [2, 0, 0, 0, 1, 0, 0, 0, 3, 1, 0, 4, 3, 0, 0, 0, 1, 2, 1, 0, 0, 0, 3, 3, 0, 4, 0, 1, 0, 0], [0, 0, 2, 2, 0, 0, 0, 3, 0, 4, 0, 4, 0, 0, 0, 0, 4, 4, 2, 2, 1, 1, 2, 4, 0, 4, 0, 0, 0, 1], [0, 0, 2, 4, 3, 0, 0, 1, 4, 0, 4, 3, 1, 3, 0, 1, 2, 0, 3, 1, 3, 0, 0, 0, 0, 1, 1, 0, 1, 0], [4, 4, 0, 4, 0, 0, 0, 0, 0, 4, 0, 4, 0, 0, 0, 4, 1, 1, 0, 0, 0, 1, 0, 0, 4, 0, 

[14, 0, 3, 5, 7, 11, 13, 15, 19, 20]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [0, 8, 19, 16, 18, 16, 22, 10, 8, 20]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [4, 12, 20, 17, 18, 19, 14, 11, 20]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [8, 12, 19, 22, 19, 14, 14, 20]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [9, 16, 19, 23, 14, 14, 20]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [10, 18, 19, 14, 15, 23]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [11, 21, 20, 14, 19]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [14, 20, 14, 19]
[[0 0 0 0 3 0 0 4 1 4 0 2 0 4 0 0 0 3]
 [0 0 3 0 4 0 0 4 0 0 0 3 4 0 1 2 0 2]
 [0 3 0 0 0 2 2 0 0 1 0 0 4 1 4 4 1 0]
 [0 0 0 0 2 2 4 4 1 0 0 0 4 1 4 4 0 0]
 [3 4 0 2 0 0 0 0 0 1 0 0 0 4 3 0 4 2]
 [0 0 2 2 0 0 4 0 4 0 0 0 2 1 0 4 0 1]
 [0 0 2 4 0 4 0 4 3 1 3 1 3 3 0 1 1 0]
 [4 4 0 4 0 0 4 0 4 0 0 4 0 0 4 0 2 0]
 [1 0 0 1 0 4 3 4 0 0 4 0 2

Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [0, 6, 12, 11, 8, 12, 3]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [4, 10, 11, 12, 12, 3]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [5, 10, 14, 15, 7]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [8, 11, 17, 10]
[[0 0 3 4 4 2 4 0 3]
 [0 0 4 4 0 3 0 1 2]
 [3 4 0 0 1 0 4 3 2]
 [4 4 0 0 0 4 0 4 0]
 [4 0 1 0 0 3 3 2 4]
 [2 3 0 4 3 0 3 0 3]
 [4 0 4 0 3 3 0 4 0]
 [0 1 3 4 2 0 4 0 3]
 [3 2 2 0 4 3 0 3 0]]
Количество внешних связей вершин:  [20, 14, 17, 16, 17, 18, 18, 17, 17]
[1, 2, 3, 5, 7, 8]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [0, 8, 4, 8, 6, 7]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [4, 4, 8, 9, 9]
Ситуация, когда контейнер меньше, чем нужно. Вектор дельт:   [5, 8, 8, 12]
[[0 3 4 4 0 3]
 [3 0 1 4 3 2]
 [4 1 0 3 2 4]
 [4 4 3 0 4 0]
 [0 3 2 4 0 3]
 [3 2 4 0 3 0]]
Количество внешних связей вершин:  [14, 13, 14, 15, 12, 12]
[4, 1, 2,